language: ruby
services: postgresql
before_script:
  - psql -c 'create database oliver_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
env:
  - DATABASE_URL=postgresql://postgres@localhost/oliver_test
rvm:
  - 2.0.0
