development:
  adapter: postgresql
  encoding: unicode
  database: oliver_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: oliver_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: oliver_production
  pool: 5
